### ISSUE TITLE
Generate MATLAB results for the binary detection

### ISSUE THREAD

**Issue by elboyran** [NLeSC/SalientDetector-matlab#6]
For both binary test images Binary_all_types_noise and Binary_nested.png

**Comment by elboyran** [comment]
The saleincy masks for the binary detector for the 2 binary test images are added. Now some Python tests fail!!!

**Comment by dafnevk** [comment]
That is because the size of the SE is now different.
@elboyran can you also output the SE for the Binary_nested image?
(like ..\tests\features\Binary\SE_all.mat for Binary_noise)

**Comment by dafnevk** [comment]
The tests fail for the Binary_noise image, because the SE has changed. How come that the SE has changed? (All parameters are still the same)

**Comment by elboyran** [comment]
I have exported the SE used for the nested image. It's called SE_nested.mat in \features\Binary
