### ISSUE TITLE
Output scores for all levels for datadriven binarization

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/SalientDetector-matlab#7]
In order to test if the data-driven binarization works correctly, I want to compare the cc-counts and scores for all considered gray levels for Gray_scale.png.
Could you output these in Matlab?

See https://github.com/NLeSC/SalientDetector-python/blob/master/Notebooks/Test_Binarizer.ipynb

**Comment by elboyran** [comment]
The arrays are exported in a MAT file @ tests/features/Gray/Num_cc.mat containing a structure 
scores with 4 fields: 
scores = 

```
           norm_num_cc: [1x255 double]
     norm_large_num_cc: [1x255 double]
norm_very_large_num_cc: [1x255 double]
       num_combined_cc: [1x255 double]
```

with commit https://github.com/NLeSC/SalientDetector-python/commit/1f5ed011ad6fd6a136576b44b2cd7ec46adb54c3. Excel sheet also updated.

**Comment by elboyran** [comment]
Now the MAT file contains directly the 4 arrays, not wrapped in a structure.

**Comment by elboyran** [comment]
2 MAT files, one containing the 'raw' number of CC arrays and their maximum values and another- the normalised arrays.

**Comment by dafnevk** [comment]
Could you update the data-driven binarized image with the new threshold (142)?
https://github.com/NLeSC/SalientDetector-python/blob/master/tests/images/Gray/Binarization_data_driven.png

**Comment by elboyran** [comment]
Updated at /tests/features/Gray/Binarization_data_driven.png with commit https://github.com/NLeSC/SalientDetector-python/commit/d515d0c8af87372e8aa0454fb78278efd31ab908

**Comment by dafnevk** [comment]
It seems like the image that you committed is still the one with threshold 146.

**Comment by elboyran** [comment]
That is strange. I have generated it today with MATLAB. I put it now in /features/ subdirectory, are you looking for it there?

**Comment by dafnevk** [comment]
Ah ok I was still looking at the one in the images, I'll delete that one.
