### ISSUE TITLE
Use parameterized connectivity in bwareaopen and hard-code 8 for imfill

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/SalientDetector-matlab#8]
in the binary detector, specifiy the connectivity when calling `imfill`

**Comment by elboyran** [comment]
I don't specify explicitly. The default value in MATLAB is 4.

**Comment by elboyran** [comment]
Commit https://github.com/NLeSC/SalientDetector-matlab/commit/370de809f73b571e2ce1e818d6172705115fdc1b
