### ISSUE TITLE
Parameterize connectivity in filling/imfill in matlab

### ISSUE THREAD

**Issue by elboyran** [NLeSC/SalientDetector-matlab#9]
_From @dafnevk on June 27, 2016 9:58_

_Copied from original issue: NLeSC/SalientDetector-python#45_

**Comment by elboyran** [comment]
I see that in the Python code (binary detector) the parameter is hard-coded to 8. Shouldn't it be also parametric? Shall we use all the same connectivity everywhere or 2 different parameters? Currently in the binary detection test the 'old' connectivity is set to 4, while the filling uses connectivity of 8. A single value requires change of MATLAB result.

**Comment by dafnevk** [comment]
Absolutely. I made [an issue](https://github.com/NLeSC/SalientDetector-python/issues/48) in the python repository.

**Comment by elboyran** [comment]
One or 2 parameters?

**Comment by dafnevk** [comment]
You mean a separate parameter for the connectivity in imfill? Would that make sense?
If possible I would just stick to one parameter.
(Although that does mean indeed that we need to rerun the detection in matlab)

**Comment by elboyran** [comment]
Separate one doesn't make much sense. Just syncing between the Python and MATLAB coding choices :-)
Also possibly a Python test/Notebook might have to be modified/rerun for the test case where the connectivity is 4 (binary detection, I think).
